//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSolid.Test.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitcoinPriceHistory
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public decimal LastPrice { get; set; }
        public decimal LastChange { get; set; }
        public decimal Volume { get; set; }
        public decimal HighPrice { get; set; }
        public decimal LowPrice { get; set; }
    }
}
